language: en
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
- name: "DucklingHTTPExtractor"
  url: "http://localhost:8000"
  dimensions: ["number"]
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy